run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - tools/protoc
    - third_party
