// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserGrpcService_Add_FullMethodName             = "/proto.UserGrpcService/Add"
	UserGrpcService_GetById_FullMethodName         = "/proto.UserGrpcService/GetById"
	UserGrpcService_GetAll_FullMethodName          = "/proto.UserGrpcService/GetAll"
	UserGrpcService_GetAllPaginated_FullMethodName = "/proto.UserGrpcService/GetAllPaginated"
	UserGrpcService_Update_FullMethodName          = "/proto.UserGrpcService/Update"
	UserGrpcService_Delete_FullMethodName          = "/proto.UserGrpcService/Delete"
	UserGrpcService_Search_FullMethodName          = "/proto.UserGrpcService/Search"
)

// UserGrpcServiceClient is the client API for UserGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserGrpcServiceClient interface {
	Add(ctx context.Context, in *UserModel, opts ...grpc.CallOption) (*ResUserMessage, error)
	GetById(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*UserModel, error)
	GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResUserList, error)
	GetAllPaginated(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ResUserPaginated, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*ResUserMessage, error)
	Delete(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*ResUserMessage, error)
	Search(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*ResUserList, error)
}

type userGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserGrpcServiceClient(cc grpc.ClientConnInterface) UserGrpcServiceClient {
	return &userGrpcServiceClient{cc}
}

func (c *userGrpcServiceClient) Add(ctx context.Context, in *UserModel, opts ...grpc.CallOption) (*ResUserMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResUserMessage)
	err := c.cc.Invoke(ctx, UserGrpcService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) GetById(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*UserModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserModel)
	err := c.cc.Invoke(ctx, UserGrpcService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResUserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResUserList)
	err := c.cc.Invoke(ctx, UserGrpcService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) GetAllPaginated(ctx context.Context, in *PaginationRequest, opts ...grpc.CallOption) (*ResUserPaginated, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResUserPaginated)
	err := c.cc.Invoke(ctx, UserGrpcService_GetAllPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*ResUserMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResUserMessage)
	err := c.cc.Invoke(ctx, UserGrpcService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) Delete(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*ResUserMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResUserMessage)
	err := c.cc.Invoke(ctx, UserGrpcService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGrpcServiceClient) Search(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*ResUserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResUserList)
	err := c.cc.Invoke(ctx, UserGrpcService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGrpcServiceServer is the server API for UserGrpcService service.
// All implementations must embed UnimplementedUserGrpcServiceServer
// for forward compatibility.
type UserGrpcServiceServer interface {
	Add(context.Context, *UserModel) (*ResUserMessage, error)
	GetById(context.Context, *UserByIdRequest) (*UserModel, error)
	GetAll(context.Context, *emptypb.Empty) (*ResUserList, error)
	GetAllPaginated(context.Context, *PaginationRequest) (*ResUserPaginated, error)
	Update(context.Context, *UpdateUserRequest) (*ResUserMessage, error)
	Delete(context.Context, *UserByIdRequest) (*ResUserMessage, error)
	Search(context.Context, *SearchUsersRequest) (*ResUserList, error)
	mustEmbedUnimplementedUserGrpcServiceServer()
}

// UnimplementedUserGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserGrpcServiceServer struct{}

func (UnimplementedUserGrpcServiceServer) Add(context.Context, *UserModel) (*ResUserMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedUserGrpcServiceServer) GetById(context.Context, *UserByIdRequest) (*UserModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedUserGrpcServiceServer) GetAll(context.Context, *emptypb.Empty) (*ResUserList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedUserGrpcServiceServer) GetAllPaginated(context.Context, *PaginationRequest) (*ResUserPaginated, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPaginated not implemented")
}
func (UnimplementedUserGrpcServiceServer) Update(context.Context, *UpdateUserRequest) (*ResUserMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserGrpcServiceServer) Delete(context.Context, *UserByIdRequest) (*ResUserMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserGrpcServiceServer) Search(context.Context, *SearchUsersRequest) (*ResUserList, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedUserGrpcServiceServer) mustEmbedUnimplementedUserGrpcServiceServer() {}
func (UnimplementedUserGrpcServiceServer) testEmbeddedByValue()                         {}

// UnsafeUserGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserGrpcServiceServer will
// result in compilation errors.
type UnsafeUserGrpcServiceServer interface {
	mustEmbedUnimplementedUserGrpcServiceServer()
}

func RegisterUserGrpcServiceServer(s grpc.ServiceRegistrar, srv UserGrpcServiceServer) {
	// If the following call panics, it indicates UnimplementedUserGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserGrpcService_ServiceDesc, srv)
}

func _UserGrpcService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).Add(ctx, req.(*UserModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).GetById(ctx, req.(*UserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).GetAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_GetAllPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).GetAllPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_GetAllPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).GetAllPaginated(ctx, req.(*PaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).Delete(ctx, req.(*UserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGrpcService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGrpcService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServiceServer).Search(ctx, req.(*SearchUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserGrpcService_ServiceDesc is the grpc.ServiceDesc for UserGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserGrpcService",
	HandlerType: (*UserGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _UserGrpcService_Add_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _UserGrpcService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _UserGrpcService_GetAll_Handler,
		},
		{
			MethodName: "GetAllPaginated",
			Handler:    _UserGrpcService_GetAllPaginated_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserGrpcService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserGrpcService_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _UserGrpcService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
