// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: user.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserModel struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	FullName      *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=full_name,proto3" json:"full_name,omitempty"`
	Avatar        *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	IsActive      *wrapperspb.BoolValue   `protobuf:"bytes,8,opt,name=is_active,proto3" json:"is_active,omitempty"`
	EmailVerified *wrapperspb.BoolValue   `protobuf:"bytes,9,opt,name=email_verified,proto3" json:"email_verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserModel) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserModel) GetUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *UserModel) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *UserModel) GetPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *UserModel) GetFullName() *wrapperspb.StringValue {
	if x != nil {
		return x.FullName
	}
	return nil
}

func (x *UserModel) GetAvatar() *wrapperspb.StringValue {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *UserModel) GetRole() *wrapperspb.StringValue {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UserModel) GetIsActive() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsActive
	}
	return nil
}

func (x *UserModel) GetEmailVerified() *wrapperspb.BoolValue {
	if x != nil {
		return x.EmailVerified
	}
	return nil
}

func (x *UserModel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserModel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserByIdRequest) Reset() {
	*x = UserByIdRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserByIdRequest) ProtoMessage() {}

func (x *UserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserByIdRequest.ProtoReflect.Descriptor instead.
func (*UserByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *UserModel             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUser() *UserModel {
	if x != nil {
		return x.User
	}
	return nil
}

type ResUserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResUserMessage) Reset() {
	*x = ResUserMessage{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResUserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResUserMessage) ProtoMessage() {}

func (x *ResUserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResUserMessage.ProtoReflect.Descriptor instead.
func (*ResUserMessage) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *ResUserMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserModel           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResUserList) Reset() {
	*x = ResUserList{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResUserList) ProtoMessage() {}

func (x *ResUserList) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResUserList.ProtoReflect.Descriptor instead.
func (*ResUserList) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *ResUserList) GetItems() []*UserModel {
	if x != nil {
		return x.Items
	}
	return nil
}

type ResUserPaginated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserModel           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResUserPaginated) Reset() {
	*x = ResUserPaginated{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResUserPaginated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResUserPaginated) ProtoMessage() {}

func (x *ResUserPaginated) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResUserPaginated.ProtoReflect.Descriptor instead.
func (*ResUserPaginated) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *ResUserPaginated) GetItems() []*UserModel {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ResUserPaginated) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\"\xfb\x04\n" +
	"\tUserModel\x12,\n" +
	"\x02id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x02id\x128\n" +
	"\busername\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\busername\x122\n" +
	"\x05email\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\x128\n" +
	"\bpassword\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\bpassword\x12:\n" +
	"\tfull_name\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\tfull_name\x124\n" +
	"\x06avatar\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x06avatar\x120\n" +
	"\x04role\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x04role\x128\n" +
	"\tis_active\x18\b \x01(\v2\x1a.google.protobuf.BoolValueR\tis_active\x12B\n" +
	"\x0eemail_verified\x18\t \x01(\v2\x1a.google.protobuf.BoolValueR\x0eemail_verified\x12:\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\"!\n" +
	"\x0fUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"I\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.proto.UserModelR\x04user\"*\n" +
	"\x0eResUserMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"5\n" +
	"\vResUserList\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.proto.UserModelR\x05items\"q\n" +
	"\x10ResUserPaginated\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.proto.UserModelR\x05items\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.proto.PaginationMetaR\n" +
	"pagination2\xc9\x04\n" +
	"\x0fUserGrpcService\x12C\n" +
	"\x03Add\x12\x10.proto.UserModel\x1a\x15.proto.ResUserMessage\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/user\x12J\n" +
	"\aGetById\x12\x16.proto.UserByIdRequest\x1a\x10.proto.UserModel\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/user/{id}\x12G\n" +
	"\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x12.proto.ResUserList\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12a\n" +
	"\x0fGetAllPaginated\x12\x18.proto.PaginationRequest\x1a\x17.proto.ResUserPaginated\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/paginated\x12V\n" +
	"\x06Update\x12\x18.proto.UpdateUserRequest\x1a\x15.proto.ResUserMessage\"\x1b\x82\xd3\xe4\x93\x02\x15:\x04user\x1a\r/v1/user/{id}\x12N\n" +
	"\x06Delete\x12\x16.proto.UserByIdRequest\x1a\x15.proto.ResUserMessage\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/user/{id}\x12Q\n" +
	"\x06Search\x12\x19.proto.SearchUsersRequest\x1a\x12.proto.ResUserList\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/users/searchB*Z(github.com/fauzie/golang-sekeleton/protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_user_proto_goTypes = []any{
	(*UserModel)(nil),              // 0: proto.UserModel
	(*UserByIdRequest)(nil),        // 1: proto.UserByIdRequest
	(*SearchUsersRequest)(nil),     // 2: proto.SearchUsersRequest
	(*UpdateUserRequest)(nil),      // 3: proto.UpdateUserRequest
	(*ResUserMessage)(nil),         // 4: proto.ResUserMessage
	(*ResUserList)(nil),            // 5: proto.ResUserList
	(*ResUserPaginated)(nil),       // 6: proto.ResUserPaginated
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 8: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*PaginationMeta)(nil),         // 10: proto.PaginationMeta
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
	(*PaginationRequest)(nil),      // 12: proto.PaginationRequest
}
var file_user_proto_depIdxs = []int32{
	7,  // 0: proto.UserModel.id:type_name -> google.protobuf.StringValue
	7,  // 1: proto.UserModel.username:type_name -> google.protobuf.StringValue
	7,  // 2: proto.UserModel.email:type_name -> google.protobuf.StringValue
	7,  // 3: proto.UserModel.password:type_name -> google.protobuf.StringValue
	7,  // 4: proto.UserModel.full_name:type_name -> google.protobuf.StringValue
	7,  // 5: proto.UserModel.avatar:type_name -> google.protobuf.StringValue
	7,  // 6: proto.UserModel.role:type_name -> google.protobuf.StringValue
	8,  // 7: proto.UserModel.is_active:type_name -> google.protobuf.BoolValue
	8,  // 8: proto.UserModel.email_verified:type_name -> google.protobuf.BoolValue
	9,  // 9: proto.UserModel.created_at:type_name -> google.protobuf.Timestamp
	9,  // 10: proto.UserModel.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: proto.UpdateUserRequest.user:type_name -> proto.UserModel
	0,  // 12: proto.ResUserList.items:type_name -> proto.UserModel
	0,  // 13: proto.ResUserPaginated.items:type_name -> proto.UserModel
	10, // 14: proto.ResUserPaginated.pagination:type_name -> proto.PaginationMeta
	0,  // 15: proto.UserGrpcService.Add:input_type -> proto.UserModel
	1,  // 16: proto.UserGrpcService.GetById:input_type -> proto.UserByIdRequest
	11, // 17: proto.UserGrpcService.GetAll:input_type -> google.protobuf.Empty
	12, // 18: proto.UserGrpcService.GetAllPaginated:input_type -> proto.PaginationRequest
	3,  // 19: proto.UserGrpcService.Update:input_type -> proto.UpdateUserRequest
	1,  // 20: proto.UserGrpcService.Delete:input_type -> proto.UserByIdRequest
	2,  // 21: proto.UserGrpcService.Search:input_type -> proto.SearchUsersRequest
	4,  // 22: proto.UserGrpcService.Add:output_type -> proto.ResUserMessage
	0,  // 23: proto.UserGrpcService.GetById:output_type -> proto.UserModel
	5,  // 24: proto.UserGrpcService.GetAll:output_type -> proto.ResUserList
	6,  // 25: proto.UserGrpcService.GetAllPaginated:output_type -> proto.ResUserPaginated
	4,  // 26: proto.UserGrpcService.Update:output_type -> proto.ResUserMessage
	4,  // 27: proto.UserGrpcService.Delete:output_type -> proto.ResUserMessage
	5,  // 28: proto.UserGrpcService.Search:output_type -> proto.ResUserList
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
